import { StyleSheet } from 'react-native';
import { theme } from '@/theme/index';

export const identificationStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.surface.background,
  },
  header: {
    paddingTop: theme.spacing.lg,
    paddingBottom: theme.spacing.lg,
    paddingHorizontal: theme.spacing.xl,
    paddingStart: theme.spacing.xl,
    paddingEnd: theme.spacing.xl,
  },
  content: {
    flex: 1,
    paddingHorizontal: theme.spacing.xl,
    paddingStart: theme.spacing.xl,
    paddingEnd: theme.spacing.xl,
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconContainer: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: theme.colors.primary[50],
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: theme.spacing.xl,
  },
  title: {
    color: theme.colors.text.primary,
    textAlign: 'center',
    marginBottom: theme.spacing['3xl'],
    fontSize: 36,
    fontWeight: '800',
    letterSpacing: -1,
    lineHeight: 44,
  },
  detailsCard: {
    backgroundColor: theme.colors.neutral[50],
    borderRadius: theme.borderRadius.xl,
    padding: theme.spacing['3xl'],
    marginBottom: theme.spacing.xl,
    width: '100%',
    borderWidth: 2,
    borderColor: theme.colors.neutral[200],
    shadowColor: theme.colors.neutral[900],
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
  },
  trustSignalsContainer: {
    marginBottom: theme.spacing['3xl'],
    width: '100%',
    alignItems: 'center',
  },
  trustSignal: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: theme.spacing.md,
  },
  trustIcon: {
    fontSize: 16,
    color: theme.colors.primary[500],
    marginRight: theme.spacing.sm,
  },
  trustTextContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  trustText: {
    color: theme.colors.text.secondary,
    fontSize: 14,
    lineHeight: 20,
  },
  trustTextBold: {
    color: theme.colors.text.primary,
    fontSize: 14,
    fontWeight: 'bold',
  },
  brandContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  brandBold: {
    color: theme.colors.primary[500],
    fontSize: 14,
    fontWeight: 'bold',
  },
  brandThin: {
    color: theme.colors.text.primary,
    fontSize: 14,
    fontWeight: '300',
  },
  serviceType: {
    color: theme.colors.text.primary,
    textAlign: 'center',
    marginBottom: theme.spacing.lg,
    fontSize: 28,
    fontWeight: '800',
    letterSpacing: -0.5,
  },
  subtitle: {
    color: theme.colors.text.secondary,
    textAlign: 'center',
    fontSize: 18,
    lineHeight: 28,
  },
  detail: {
    color: theme.colors.text.primary,
    marginBottom: theme.spacing.sm,
  },
  trustText: {
    color: theme.colors.text.secondary,
    textAlign: 'center',
  },
  bottomSection: {
    paddingHorizontal: theme.spacing.xl,
    paddingStart: theme.spacing.xl,
    paddingEnd: theme.spacing.xl,
    paddingBottom: theme.spacing['2xl'],
  },
  buttonRow: {
    gap: theme.spacing.md,
  },
  noButton: {
    backgroundColor: theme.colors.neutral[50],
    borderWidth: 2,
    borderColor: theme.colors.neutral[300],
    paddingVertical: theme.spacing.xl,
    paddingHorizontal: theme.spacing['2xl'],
    borderRadius: theme.borderRadius.xl,
    alignItems: 'center',
  },
  noButtonText: {
    color: theme.colors.text.secondary,
    fontSize: 20,
    fontWeight: '600',
  },
  continueButton: {
    backgroundColor: theme.colors.primary[500],
    paddingVertical: theme.spacing.xl,
    paddingHorizontal: theme.spacing['2xl'],
    borderRadius: theme.borderRadius.xl,
    alignItems: 'center',
    shadowColor: theme.colors.primary[500],
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 12,
  },
  continueButtonText: {
    color: theme.colors.text.inverse,
    fontSize: 20,
    fontWeight: '800',
    letterSpacing: 1,
  },
});
