import * as admin from 'firebase-admin';
import { onCall } from 'firebase-functions/v2/https';
import { createOrder } from './functions/createOrder';
import { getOrder } from './functions/getOrder';
import { getProducts } from './functions/getProducts';
import { getProduct } from './functions/getProduct';
import { updateProduct } from './functions/updateProduct';
import { deleteProduct } from './functions/deleteProduct';
import { updateOrderStatus } from './functions/updateOrderStatus';
import { getOrders } from './functions/getOrders';
import { getProductsAdmin } from './functions/getProductsAdmin';
import { createProduct } from './functions/createProduct';
import { checkAdminStatus } from './functions/checkAdminStatus';
import { getPaymentSettings } from './functions/getPaymentSettings';
import { updatePaymentSettings } from './functions/updatePaymentSettings';

admin.initializeApp();

export const createOrderFnV2 = onCall(createOrder);
export const getOrderFnV2 = onCall(getOrder);
export const getProductsFnV2 = onCall(getProducts);
export const getProductFnV2 = onCall(getProduct);
export const updateProductFnV2 = onCall(updateProduct);
export const deleteProductFnV2 = onCall(deleteProduct);
export const updateOrderStatusFnV2 = onCall(updateOrderStatus);
export const getOrdersFnV2 = onCall(getOrders);
export const getProductsAdminFnV2 = onCall(getProductsAdmin);
export const createProductFnV2 = onCall(createProduct);
export const checkAdminStatusFnV2 = onCall(checkAdminStatus);
export const getPaymentSettingsFnV2 = onCall(getPaymentSettings);
export const updatePaymentSettingsFnV2 = onCall(updatePaymentSettings);
